title: JO's Courses
logo: /assets/img/gccycCOL.png
description: Quantum and Scientific Computing Group.
show_downloads: true
google_analytics: quantum computing, scientific computing, quantum machine learning
theme: jekyll-theme-minimal
